### ISSUE TITLE
Invalid orbit in contract (Kolniya around the Mun)

### ISSUE THREAD

**Issue by chippydip** [linuxgurugamer/UnmannedContracts#2]
I just accepted this contract, launched a ship, and started messing with maneuver nodes before I realized it's impossible to complete:

![image](https://cloud.githubusercontent.com/assets/552649/17354837/db8254c0-5900-11e6-8de0-72dd7c5aafe9.png)

The Mun's SOI is only 2229km so it's impossible to get a 3584km AP. I'm guessing this may be an issue with other slow-rotating bodies.

**Comment by linuxgurugamer** [comment]
this was fixed a while ago
